# Generated by Django 5.0.1 on 2024-01-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_populate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('video_id', models.CharField(max_length=100)),
                ('video_title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('published_time', models.DateTimeField()),
                ('thumbnails', models.JSONField()),
                ('urls', models.URLField()),
                ('channel_name', models.CharField(blank=True, max_length=100, null=True)),
                ('channel_id', models.CharField(max_length=100)),
            ],
            options={
                'indexes': [models.Index(fields=['published_time'], name='db_populate_publish_80f9f9_idx')],
            },
        ),
    ]
